const authProviders = [
  { name: 'google' },
  { name: 'facebook' },
  { name: 'github' },
];

const contests = [
  {
    id: 1,
    title: 'hash map',
    slug: `hash-map-${Date.now()}`,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
  },
  {
    id: 2,
    title: 'sort',
    slug: `sort-${Date.now()}`,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
  },
  {
    id: 3,
    title: 'starter',
    slug: `starter-${Date.now()}`,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
  },
];

const plans = [
  {
    id: 1,
    name: 'free',
    creditsPerMonth: 100,
    pricePerMonth: 0,
  },
  {
    id: 2,
    name: 'premium',
    creditsPerMonth: 1000,
    pricePerMonth: 100,
  },
];

const challenges = [
  {
    id: 1,
    title: 'diff two array',
    slug: `diff-two-array-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'easy',
    points: 100,
    isPremium: false,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 2,
    title: 'selection sort',
    slug: `selection-sort-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'easy',
    points: 100,
    isPremium: false,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 2,
  },
  {
    id: 3,
    title: 'binary sort',
    slug: `binary-sort-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'medium',
    points: 200,
    isPremium: false,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 2,
  },
  {
    id: 4,
    title: 'quick sort',
    slug: `quick sort-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'medium',
    points: 200,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 5,
    title: 'merge sort',
    slug: `merge sort-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'hard',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 6,
    title: 'find the symmetric difference',
    slug: `find-the-symmetric-difference-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'hard',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 7,
    title: 'inventory update',
    slug: `inventory-update-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'hard',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 8,
    title: 'no repeats please',
    slug: `no-repeats-please-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'hard',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 9,
    title: 'pairwise',
    slug: `pairwise-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'hard',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 10,
    title: 'diff two arrays',
    slug: `diff-two-arrays-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 11,
    title: 'dna pairing',
    slug: `dna-pairing-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 12,
    title: 'drop it',
    slug: `drop-it-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 13,
    title: 'everything be true',
    slug: `everything-be-true-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 14,
    title: 'missing letters',
    slug: `missing-letters-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 15,
    title: 'pig latin',
    slug: `pig-latin-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 16,
    title: 'sorted union',
    slug: `sorted-union-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 17,
    title: 'sales by match',
    slug: `sales-by-match-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 18,
    title: 'counting valleys',
    slug: `counting-valleys-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 19,
    title: 'jumping on the clouds',
    slug: `jumping-on-the-clouds-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 20,
    title: 'repeated string',
    slug: `repeated-string-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 21,
    title: '2D array - DS',
    slug: `2D-array-DS-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 22,
    title: 'arrays: left rotation',
    slug: `arrays:-left-rotation-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 23,
    title: 'new year chaos',
    slug: `new-year-chaos-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'medium',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 24,
    title: 'minimum swaps 2',
    slug: `minimum-swaps-2-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'medium',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
  {
    id: 25,
    title: 'array manipulation',
    slug: `array-manipulation-${new Date()}`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    challengeSeed: '',
    level: 'hard',
    points: 300,
    isPremium: true,
    createAt: new Date(),
    updateAt: new Date(),
    deleteAt: null,
    contestId: 1,
  },
];

const testCases = [
  {
    text: '',
    testString:
      'assert.sameMembers(diffArray(["diorite", "andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"]), ["pink wool"]);',
    challengeId: 1,
  },
  {
    text: '',
    testString:
      'assert(diffArray(["diorite", "andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"]).length === 1);',
    challengeId: 1,
  },
  {
    text: '',
    testString:
      'assert.sameMembers(diffArray(["andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"]), ["diorite", "pink wool"]);',
    challengeId: 1,
  },
  {
    text: '',
    testString:
      'assert(diffArray(["andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"]).length === 2);',
    challengeId: 1,
  },
];

const subscriptions = [
  {
    startTime: new Date(),
    endTime: new Date(2020, 9),
    planId: 2,
    userId: 1,
  },
  {
    startTime: new Date(),
    endTime: new Date(2099, 9),
    planId: 1,
    userId: 2,
  },
];

module.exports = {
  authProviders,
  contests,
  challenges,
  plans,
  testCases,
  subscriptions,
};
