services:
  redis:
    image: redis:6.2.4
    ports:
      - '6380:6379'
    networks:
      - default
  database:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB: ${DATABASE_NAME}
    ports:
      - '1234:${DATABASE_PORT}'
    networks:
      - default
    volumes:
      - ../user-service-database-data:/var/lib/postgresql/data
      - ./tools/scripts/database:/docker-entrypoint-initdb.d
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - database
      - redis
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      KAFKA_HOST: kafka
      REDIS_HOST: redis
    ports:
      - '${APP_PORT}:3001'
    networks:
      - default
      - network-topic-channel
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
volumes: {}
networks:
  network-topic-channel:
    external:
      name: kafka_network-topic-channel
