services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}"
    networks:
      - default
    volumes:
      - auth-service-database-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - "${APP_PORT}:3000"
    networks:
      - default
      - network-topic-channel
    volumes:
      - ".:/app"
      - "/app/node_modules"
      - "/app/dist"
volumes:
  auth-service-database-data: {}
networks:
  network-topic-channel:
    external:
      name: kafka_network-topic-channel
